### ISSUE TITLE
💡 Guide on getting HW acceleration working

### ISSUE THREAD

**Issue by djtecha** [beluga-cloud/charts#302]
### How these charts can be improved?

Hello,
I was wondering if there's any documentation on getting hw trans-coding working with this cart? Trying to follow this guide and translate it to your chart: https://jellyfin.org/docs/general/administration/hardware-acceleration/intel/

Looks like I have the DRI device mounted but it fails to initialize. The device on the hows has group access for render and that group id is 104

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyfin
      version: "2.3.0"
      sourceRef:
        kind: HelmRepository
        name: beluga-cloud
        namespace: cluster-config
  values:
    podSecurityContext:
      runAsNonRoot: true
      fsGroup: 911
      seccompProfile:
        type: RuntimeDefault
      runAsUser: 911
      runAsGroup: 911
      supplementalGroups:
        - 104
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 911
      runAsGroup: 911
      supplementalGroups:
        - 104
    jellyfin:
      extraDevices:
        - /dev/dri/renderD128
```       

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by djjudas21** [comment]
Thanks for the pointers, @djtecha. I got this working on my cluster by specifying the uid as `64710`, which is the default in the helm chart.

I also specified the GPU as a requestable resource, to make sure the pod gets scheduled on a node with a GPU - and that other GPU workloads will be scheduled on a different node. The GPU must be specified in `requests` **and** `limits`.

```yaml
resources:
  jellyfin:
    requests:
      cpu: 500m
      memory: 512Mi
      gpu.intel.com/i915: "1"
    limits:
      cpu: '4'
      memory: 6Gi
      gpu.intel.com/i915: "1"
```

(yes, I know Intel i915 is ancient, lol)

I'm planning a blog post on how I set up the device allocation, but basically it's using [node-feature-discovery](https://artifacthub.io/packages/helm/node-feature-discovery/node-feature-discovery), [intel-device-plugins-operator](https://artifacthub.io/packages/helm/intel/intel-device-plugins-operator) and [intel-device-plugins-gpu](https://artifacthub.io/packages/helm/intel/intel-device-plugins-gpu)
